name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Cambia a '16' o '20' para evitar la advertencia

      - name: Install dependencies
        run: npm install
        working-directory: ./TiendaArtLimp  # Ajusta si es necesario

      - name: Run tests
        run: npm test
        working-directory: ./TiendaArtLimp  # Ajusta si es necesario

